### ISSUE TITLE
[bug] When 0 value in a Cost Estimation Print job doesn't save and gives errors

### ISSUE THREAD

**Issue by madnlooney** [OllisGit/OctoPrint-PrintJobHistory#181]
octoprint Version 1.7.2
latest printjobhistory 1.15.2
Cost Estimation (3.4.0)

No reports were recorded when the Cost Estimation plugin has a 0 value.

In cost estimation plugin i had Purchase price, Estimated lifespan and Maintenance costs all set to 0?

Errors below in the log

```
2021-11-22 14:12:09,077 - octoprint.plugin - ERROR - Error while calling plugin PrintJobHistory
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1737, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_PrintJobHistory/__init__.py", line 976, in on_event
    self._printJobFinished("success", payload)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_PrintJobHistory/__init__.py", line 753, in _printJobFinished
    self._addCostsToPrintModel(self._currentPrintJobModel)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_PrintJobHistory/__init__.py", line 684, in _addCostsToPrintModel
    costData = self._costEstimationPluginImplementation.api_getCurrentCostsValues()
AttributeError: 'CostEstimationPlugin' object has no attribute 'api_getCurrentCostsValues'
```

**Comment by OllisGit** [comment]
Hi @madnlooney! 
hmm...it looks like there is something wrong with the installation of the Cost-Plugin, because it has nothing to do with 0 values.
Please uninstall the Cost-Plugin and then reinstall it.

If the issue still occurs, please attach the full octoprint.log
