### ISSUE TITLE
 PrintJobHistory not capturing my prints 

### ISSUE THREAD

**Issue by pepesz** [OllisGit/OctoPrint-PrintJobHistory#208]
Hello,

I installed the PrintJobHistory on my octoprint, however it does not capturing prints.

OctoPrint 1.8.6 Python 3.7.3 OctoPi 0.18.0

I see error in octoprint.log file at the end of print:
```
2022-11-28 15:00:47,993 - octoprint.plugin - ERROR - Error while calling plugin PrintJobHistory
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 273, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_PrintJobHistory/__init__.py", line 1309, in on_event
    self._printJobFinished("success", payload)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_PrintJobHistory/__init__.py", line 938, in _printJobFinished
    self._capturePrintJobData(printStatus, payload)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_PrintJobHistory/__init__.py", line 984, in _capturePrintJobData
    self._addCostsToPrintModel(self._currentPrintJobModel)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_PrintJobHistory/__init__.py", line 726, in _addCostsToPrintModel
    costData = self._calculateCostData(allFilamentModels , printTimeInSeconds)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_PrintJobHistory/__init__.py", line 829, in _calculateCostData
    if (allFilamentModels[0].usedLength is None):
IndexError: list index out of range

```

Thank you in advance.

**Comment by PowerShellCrack** [comment]
I'm gettiin the same issue but its saying my database is locked

![image](https://user-images.githubusercontent.com/20599825/206167735-756c15e2-cf3b-41a5-933c-90be0f8d83d1.png)

OctoPrint 1.8.6
Python 3.7.3
OctoPi 0.18.0
PrintJobHistory: 1.17.0
