### ISSUE TITLE
Prusa Slicer Thumbnail

### ISSUE THREAD

**Issue by TMTYD** [OllisGit/OctoPrint-PrintJobHistory#224]
The thumbnails are not saved in the Print job History, although I have installed the Prusaslicer Thumbnail plugin and have also specified the values for Thumbnail in PrusaSlicer under Print settings. Why is that?

![grafik](https://github.com/OllisGit/OctoPrint-PrintJobHistory/assets/29516076/0b12d79f-336a-4473-a58a-7434f48a681f)

[Technical Log](https://privatebin.net/?cad487d3efe44c54#2dJMmtRURwm2Kv9cAKMCnxnfaZq1uD4jrRQWiNSvXceP)

**Comment by TMTYD** [comment]
i have this in log from octoprint.log

```
octoprint - ERROR - Exception on /plugin/PrintJobHistory/printJobSnapshot/20230813-013948.jpg [GET]
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/OctoPrint/venv/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/OctoPrint/venv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/OctoPrint/venv/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/pi/OctoPrint/venv/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/OctoPrint/venv/lib/python3.9/site-packages/octoprint_PrintJobHistory/api/PrintJobHistoryAPI.py", line 443, in get_snapshot
    return send_file(absoluteFilename, mimetype='image/jpg', cache_timeout=1)
TypeError: send_file() got an unexpected keyword argument 'cache_timeout'
```

**Comment by dojohnso** [comment]
@TMTYD try the fix I have a PR open for here:

https://github.com/OllisGit/OctoPrint-PrintJobHistory/pull/216/commits/1d86931381f7bb7492a20a8c8f7e73e09cf1bc73

I'm working on trying to get this plugin flagged as abandoned so we can actually get some updates to it

**Comment by TMTYD** [comment]
[plugin_PrintJobHistory_singlePrintJob.log](https://github.com/OllisGit/OctoPrint-PrintJobHistory/files/12790139/plugin_PrintJobHistory_singlePrintJob.log)
Hi, I changed that, but unfortunately no improvement. What size must be set in the Prusa slicer for G-code thumbnails? I set 16x16, 200x200 there and png as the format

**Comment by dojohnso** [comment]
> [plugin_PrintJobHistory_singlePrintJob.log](https://github.com/OllisGit/OctoPrint-PrintJobHistory/files/12790139/plugin_PrintJobHistory_singlePrintJob.log) Hi, I changed that, but unfortunately no improvement. What size must be set in the Prusa slicer for G-code thumbnails? I set 16x16, 200x200 there and png as the format

that's what mine is set to as well. i've noticed this fix doesn't work for everyone, even on one of my Pi's it's not working but I haven't gotten into why yet. Likely will have to do with versions of board or OS or python, etc.

**Comment by TMTYD** [comment]
Hi why does it sometimes work and sometimes not?

![grafik](https://github.com/OllisGit/OctoPrint-PrintJobHistory/assets/29516076/bc1a920f-f221-4c08-9280-be33d4f152ad)

**Comment by Titius-Sicanus** [comment]
If the file name contains spaces or special characters then the thumbnail is not extracted.
The only characters I've found allowed are the minus sign (-) and the underscore character (_)

**Comment by TMTYD** [comment]
Ok, can you change that somehow?

**Comment by Titius-Sicanus** [comment]
I'm sorry but I'm also waiting for someone to be able to solve this problem.

**Comment by dojohnso** [comment]
If octoprint ever acknowledges this plugin is abandoned and someone takes it over (I've been trying for months), best I can do is take a look and maybe submit another PR that people can see and copy the changes locally.

**Comment by TMTYD** [comment]
> If the file name contains spaces or special characters then the thumbnail is not extracted.
> The only characters I've found allowed are the minus sign (-) and the underscore character (_)

So that works with the _ substir, then the thumbnail is also saved

**Comment by dojohnso** [comment]
@TMTYD @Titius-Sicanus 

https://github.com/OllisGit/OctoPrint-PrintJobHistory/pull/226
