### ISSUE TITLE
Error after job finished

### ISSUE THREAD

**Issue by blalor** [OllisGit/OctoPrint-PrintJobHistory#65]
Plugin v1.5.0
OctoPrint v1.4.1
Python v3.8.3

gcode: [Treefrog_0.2mm_FLEX_MK3S_1h5m.gcode](https://github.com/OllisGit/OctoPrint-PrintJobHistory/files/4931454/Treefrog_0.2mm_FLEX_MK3S_1h5m.gcode.txt.gz)

```
2020-07-16 11:13:21,160 - octoprint.plugins.PrintJobHistory - INFO - Print result:success, CaptureMode:successful
2020-07-16 11:13:21,160 - octoprint.plugins.PrintJobHistory - INFO - Start capturing print job
2020-07-16 11:13:21,180 - octoprint.plugins.PrintJobHistory.SlicerSettingsParser - INFO - Start parsing Slicer-Settings
2020-07-16 11:13:23,153 - octoprint.plugin - ERROR - Error while calling plugin PrintJobHistory
Traceback (most recent call last):
  File "/opt/octoprint-venv/lib/python3.8/site-packages/OctoPrint-1.4.0-py3.8.egg/octoprint/plugin/__init__.py", line 224, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/opt/octoprint-venv/lib/python3.8/site-packages/octoprint_PrintJobHistory/__init__.py", line 501, in on_event
    self._printJobFinished("success", payload)
  File "/opt/octoprint-venv/lib/python3.8/site-packages/octoprint_PrintJobHistory/__init__.py", line 364, in _printJobFinished
    slicerSettings = SlicerSettingsParser(self._logger).extractSlicerSettings(selectedFile, None)
  File "/opt/octoprint-venv/lib/python3.8/site-packages/octoprint_PrintJobHistory/common/SlicerSettingsParser.py", line 73, in extractSlicerSettings
    line = self.nextReversedLine(fileHandle, lastTopFilePosition)
  File "/opt/octoprint-venv/lib/python3.8/site-packages/octoprint_PrintJobHistory/common/SlicerSettingsParser.py", line 175, in nextReversedLine
    next_char = fileHandle.read(1)
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte
```

If I had to guess I'd say maybe the `→` is causing issues:

```
; filament_notes = "https://www.amazon.com/dp/B07VBKDM74?th=1\nhttps://overture3d.com/products/overture-tpu-filament-1-75mm?variant=31150363541581\n\nsettings derived from NinjaFlex\n\nRecommended Extrusion/Nozzle Temp: 210-230°C\nHeated Bed Temp: 25-60°C\nFilaments Diameter and Accuracy: 1.75 mm +/- 0.05\n\nTurn of autoload, minimal tension. Use painter's tape.\nStringy af.\n\nOverriding retraction (affects Printer Settings → Extruder 1 → Retraction, I think) results in this weirdness:\nhttps://github.com/prusa3d/PrusaSlicer/issues/4113"
```

**Comment by OllisGit** [comment]
Hi @blalor,

your PR is now in the latest version 1.6.0. 

Thanks again for your support.
Olli
